import = ["~/.config/alacritty/colors.toml"]
[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 12
offset = { x = -1, y = -2}  # <-- this adds spacing between letters
[window]
opacity = 0.65
dimensions = { columns =120, lines =35}
padding = { x = 5, y = 5}  
